name: Test Python 

on:
  workflow_dispatch:

jobs:
  build:
    name: Build distribution 📦
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.13', 'pypy3.10', 'graalpy-24.0', '3.14.0-alpha.1', '3.14-dev', '>=3.9 <3.14', 'python 3.13.0-alpha - 3.13.0','3.x', 'pypy3.10', 'pypy-3.10', 'pypy3.9', 'pypy-3.9', 'pypy3.7-v7.3.3', 'pypy-3.7-v7.3.3', 'pypy3.7-v7.x', 'pypy-3.7-v7.x', 'pypy3.7-v7.3.3rc1', 'pypy-3.7-v7.3.3rc1', 'pypy3.7-nightly', 'pypy-3.7-nightly']
        os: [ubunutu-latest, windows-latest, macos-latest]
        arch: [x86, x64]
        
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: mahabaleshwars/setup-python@feature/tool-versions-file-support
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.arch }}
            
