name: test
on:
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Get Python version
        run: python --version
      - name: Get pipx version
        run: pipx --version
      - name: Install Python Package
        run: pipx install .