name: Python Version Test

on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8.17', '3.13.0', '3.12.3', '3.14.0-alpha.1']
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]
        exclude:
          - os: macos-latest
            python-version: 3.8.17
          - os: windows-latest
            python-version: 3.8.17  
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: priyagupta108/setup-python@create_release
        with:
          python-version: ${{ matrix.python-version }}
      - name: Get Python version
        run: python --version
      - name: Install dependencies
        run: pip install -r requirements.txt
     
