name: Test PR Changes that is without hardcoded AGENT_TOOLSDIRECTORY on macOS
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted, Linux]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
     
    
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

     
      - name: Check Python Version with Sudo
        run: |
          PYTHON_PATH=$(which python3)
          sudo $PYTHON_PATH --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
