name: Test PR Changes that is without hardcoded AGENT_TOOLSDIRECTORY on macOS
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ Linux ]
        # python-version: ['3.10', '3.12']
        python-version: ['3.10']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Display environment variables
        run: |
          echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
          echo "LIBRARY_PATH: $LIBRARY_PATH"
      - name: Check Python version
        run: python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
