name: Test PR Changes that is without hardcoded AGENT_TOOLSDIRECTORY on macOS
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted, Linux]
    strategy:
      matrix:
        # python-version: ['3.10', '3.12']
        python-version: ['3.9']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Ensure Sudo is Installed
        run: |
          if ! command -v sudo &> /dev/null; then
            echo "sudo could not be found. Installing..."
            sudo apt-get update && sudo apt-get install -y sudo
          fi
    
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

     
      - name: Check Python version
        run: sudo python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
