name: Build and Publish Flask Python App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: priyagupta108/setup-python@test
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build the application
        run: python setup.py sdist

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: flask-app
          path: ./dist/flask-app-*.tar.gz

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: flask-app
          path: ./

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v2
        with:
          python-version: '3.x'
          build-script-path: ./setup.py
    
          token: ${{ secrets.PYPI_API_TOKEN }}

